// <auto-generated />
namespace MusicStoreSite.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class ProductGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "201409040756182_ProductGenre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
